S5 no more /tmp jen-op-9304666r

diff --git a/jen-op-9304666r b/jen-op-9304666r
--- a/jen-op-9304666r
+++ b/jen-op-9304666r
@@ -111,32 +111,18 @@ stage('Op-9304666r-S5') {
         script {
             echo "Op-9304666r-S5: Performing web test on Prod server"
 
-            // Run curl test FROM HOST to host port 33500
+            // Curl against host port 33500, write result into prod-result-file
             sh """
-                // curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file || echo "FAIL" > /tmp/prod-result-file
-                // curl -Is http://localhost:33500 | head -n 1 | sudo tee /tmp/prod-result-file > /dev/null || echo "FAIL" | sudo tee /tmp/prod-result-file > /dev/null
-                // docker exec -u root 9304666r-prod-svr sh -c "curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file || echo 'FAIL' > /tmp/prod-result-file"
-                // docker exec 9304666r-prod-svr sh -c "curl -Is http://localhost:33500 | head -n 1 | tee /tmp/prod-result-file >/dev/null || echo 'FAIL' | tee /tmp/prod-result-file"
-                // docker exec 9304666r-prod-svr sh -c "curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file || echo FAIL > /tmp/prod-result-file"
-                // docker cp 9304666r-prod-svr:/tmp/prod-result-file ${WORKSPACE}/prod-result-file
-                // docker exec 9304666r-prod-svr sh -c "curl -Is http://localhost:33500 | head -n 1 > /operate/9304666r/tmp/prod-result-file || echo FAIL > /operate/9304666r/tmp/prod-result-file"
-                // docker cp 9304666r-prod-svr:/operate/9304666r/tmp/prod-result-file ${WORKSPACE}/prod-result-file
-                docker exec 9304666r-prod-svr sh -c "curl -Is http://localhost:33500 | head -n 1 > /tmp/prod-result-file || echo FAIL > /tmp/prod-result-file"
-                docker cp 9304666r-prod-svr:/tmp/prod-result-file ${WORKSPACE}/prod-result-file
+                curl -Is http://localhost:33500 | head -n 1 > prod-result-file || echo "FAIL" > prod-result-file
             """
 
             // Read the result
-            // def prodResult = sh(script: "head -n 1 /tmp/prod-result-file", returnStdout: true).trim()
-            // if (prodResult != "HTTP/1.1 200 OK") {
-            //    error("Prod web test failed! Got result: ${prodResult}")
-            //} else {
-            //    echo "Prod web test passed!"
-            def prodResult = readFile("${WORKSPACE}/prod-result-file").trim()
-            if (prodResult.contains("200")) {
+            def prodResult = readFile('prod-result-file').trim()
+
+            if (prodResult == "HTTP/1.1 200 OK") {
                 echo "Prod web test passed!"
             } else {
-                error("Prod web test failed! Got: ${prodResult}")
-
+                error("Prod web test failed! Got result: ${prodResult}")
             }
         }
     }
@@ -177,6 +163,7 @@ stage('Op-9304666r-S5') {
         }
     }
 }
+
 
 
 
