Update jen-op-9304666r

diff --git a/jen-op-9304666r b/jen-op-9304666r
--- a/jen-op-9304666r
+++ b/jen-op-9304666r
@@ -53,12 +53,12 @@ pipeline {
                         echo "Op-9304666r-S3: Proceed to roll out to Prod server"
                     } else {
                         sh """
-                            echo "Op-9304666r-S3: QA server fails after update and is rolled back"
-                            docker stop ${QA_NAME} || true
-                            docker rm ${QA_NAME} || true
-                            docker run -d --name ${QA_NAME} qa-bkup-image
-                        """
-                        error("Aborting")
+    echo "Op-9304666r-S3: QA server fails after update and is rolled back"
+    docker stop ${QA_NAME} || true
+    docker rm ${QA_NAME} || true
+    docker run -d --name ${QA_NAME} -p 33200:80 qa-bkup-image
+"""
+error("Aborting")
                     }
                 }
             }
@@ -122,4 +122,5 @@ pipeline {
         }
     }
 }
+
 
